# Build stage
FROM golang:1.24 as builder

WORKDIR /app

# First copy only dependency files for better layer caching
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application
COPY . .

# Build the application
RUN go build -ldflags="-s -w" -o telegram-deepseek-bot main.go

# Runtime stage
FROM debian:stable-slim

SHELL [ "/bin/sh", "-ec" ]

RUN export DEBCONF_NONINTERACTIVE_SEEN=true \
    DEBIAN_FRONTEND=noninteractive \
    DEBIAN_PRIORITY=critical \
    TERM=linux ; \
    apt-get -qq update ; \
    apt-get -yyqq upgrade ; \
    apt-get -yyqq install ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# (Optional) Create non-root user for security
RUN useradd -mU appuser && mkdir -p /data /log && \
    chown -R appuser:appuser /data /log

# Copy only necessary files from builder
COPY --from=builder --chown=appuser /app/telegram-deepseek-bot /telegram-deepseek-bot
COPY --from=builder --chown=appuser /app/conf /conf

WORKDIR /
USER appuser:appuser

# Runtime command
CMD ["/telegram-deepseek-bot"]
